proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name = 'adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
    path('locatii_inactive', views.LocationsInactiveView.as_view(), name='locatii_inactive'),
]

proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompaniesView.as_view(), name='lista_companii'),
    path('adaugare/', views.CreateCompaniesView.as_view(), name = 'adauga'),
    path('<int:pk>/update/', views.UpdateCompaniesView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_company, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_company, name='activeaza'),
    path('companii_inactive', views.CompaniesInactiveView.as_view(), name='companii_inactive'),
]

proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()   #aceasta comanda se ocupa de routare
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('profile/', include('userprofile.urls')),
]

proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
]

proiect/templates/base.html
<html>
    <head>
        {% block title %}
        {% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav>
                        <a class="btn" href="/admin">Admin</a>
                        {% if request.user.is_authenticated %}
                            <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii active</a>
                            <a class="btn" href="{% url 'locations:locatii_inactive' %}">Locatii inactive</a>
                            <a class="btn" href="{% url 'userprofile:utilizator_nou' %}">Adaugare utilizator</a>
                            <a class="btn" href="{% url 'companies:lista_companii' %}">Aplicatie Companii</a>
                            <a class="btn" href="{% url 'companies:companii_inactive' %}">Companii inactive</a>
                            <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                        {% endif %}
                    </nav>
                </div>
            </div>

        </div>
        <br>
        <br>
        {% block content %}
        {% endblock %}
    </body>
</html>