ProiectFinal/ProiectWebFinal/Application1/urls.py
from django.urls import path

from Application1 import views

app_name = 'reportwriter'

urlpatterns = [
    path('', views.ProjectsView.as_view(), name='project_list'),
    path('add/', views.CreateProjectsView.as_view(), name='add_project'),
    path('<int:pk>/update/', views.UpdateProjectsView.as_view(), name='modify_project'),
    path('<int:pk>/assign_engineer/', views.AssignEngineerView.as_view(), name='assign_engineer'),
    path('<int:pk>/delete/', views.delete_project, name='delete_project'),
    path('<int:pk>/activate/', views.activate_project, name='activate_project'),
    path('<int:pk>/run_quote/', views.run_quote, name='generate_quote'),
    path('<int:pk>/download_quote/', views.download_quote, name='download_quote'),
    path('<int:pk>/quote_accepted/', views.quote_accepted, name='quote_accepted'),
    path('<int:pk>/generate_report/', views.generate_report, name='generate_report'),
    path('<int:pk>/download_report/', views.download_report, name='download_report'),
    path('closed_projects', views.ProjectsClosedView.as_view(), name='closed_projects'),
    # path('rundocx/', name='generate_doc_report'),
]

ProiectFinal/ProiectWebFinal/ProiectWebFinal/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('reportwriter/', include('Application1.urls')),
    path('finance/', include('Application2.urls')),
    path('profile/', include('users.urls')),
    path('home/', include('home.urls')),
    path('about/', include('home.urls')),
    # path('annual_leave/', include('Application3.urls')),
]

ProiectFinal/ProiectWebFinal/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.CreateHomeView.as_view(), name='home'),
    path('about', views.CreateAboutView.as_view(), name='about'),
]

ProiectFinal/ProiectWebFinal/Application1/models.py
from datetime import date

from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
users = User.objects.all()
# print(users[0].first_name)
engineer_choices=[]
for eng in users:
     engineer_choices.append((str(eng.first_name)+" "+str(eng.last_name),str(eng.first_name)+" "+str(eng.last_name)))
# print(engineer_choices)

# Create your models here.

class Reporting(models.Model):

    project_name = models.CharField(max_length=100)
    project_address = models.CharField(max_length=300)
    project_value=models.BigIntegerField(default=0)
    client_company=models.CharField(max_length=50, default='')
    client_representative=models.CharField(max_length=100, default='')
    building_height=models.BigIntegerField(default=0)
    building_type=models.CharField(max_length=50)
    number_of_stairs=models.BigIntegerField(default=0)
    active = models.BooleanField(default=1)
    quote_produced = models.BooleanField(default=0)
    quote_issued = models.BooleanField(default=0)
    quote_accepted = models.BooleanField(default=0)
    report_generated = models.BooleanField(default=0)
    report_issued = models.BooleanField(default=0)
    request_date = models.CharField(default=str(date.today()), max_length=100)
    project_fee = models.CharField(default='NA', max_length=10)
    assigned_engineer = models.CharField(max_length=45, default="NA", choices=engineer_choices)
    invoice_generated = models.BooleanField(default=0)
    invoice_issued = models.BooleanField(default=0)
    # profile_pic = models.ImageField(upload_to=user_directory_path, null=True, blank=True) pentru poze
    # profile_pic = models.ImageField(upload_to=‘ / covers’, null = True, blank = True)

    def __str__(self):
        return f"{self.building_type}"

ProiectFinal/ProiectWebFinal/home/models.py
from django.db import models

# Create your models here.

ProiectFinal/ProiectWebFinal/Application1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
import mimetypes
import os
from django.http.response import HttpResponse

from Application1.models import Reporting

from Application1.mailmergerunner import mailmergefunction_quotes

from Application1.mailmergerunner import mailmergefunction_reports

class ProjectsView(LoginRequiredMixin, ListView):
    model = Reporting
    template_name = 'Application1/projects_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=1)
    context_object_name = 'projects'

    def get_context_data(self, *args, **kwargs):
        data=super(ProjectsView, self).get_context_data()
        # data['reporting_list'] = self.model.objects.filter(active=1)
        return data

class ProjectsClosedView(LoginRequiredMixin, ListView):
    model = Reporting     #Este modelul declarat in models.py
    template_name = 'Application1/projects_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=0)
    context_object_name = 'projects'

    def get_context_data(self, *args, **kwargs):
        data=super(ProjectsClosedView, self).get_context_data(*args, **kwargs)
        # data['reporting_list'] = self.model.objects.filter(active=0)
        return data

class CreateProjectsView(LoginRequiredMixin, CreateView):
    model = Reporting
    fields = ['project_name', 'project_address', 'project_value', 'client_company', 'client_representative', 'building_height', 'building_type', 'number_of_stairs']
    template_name ='Application1/project_form.html'
    counter = 1

    def get_success_url(self):
        self.counter += 1
        return reverse('reportwriter:project_list')

class UpdateProjectsView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Reporting
    fields = ['project_name', 'project_address', 'project_value', 'client_company', 'client_representative', 'building_height', 'building_type', 'number_of_stairs']
    template_name ='Application1/project_form.html'

    def get_success_url(self):
        return reverse('reportwriter:project_list')

    def test_func(self):                             #de facut la toate
        if self.request.user.is_authenticated:
            return True
        return False

class AssignEngineerView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Reporting
    fields = ['assigned_engineer']
    template_name = 'Application1/assign_engineer.html'

    def get_success_url(self):
        return reverse('reportwriter:project_list')

    def test_func(self):                             #de facut la toate
        if self.request.user.is_authenticated:
            return True
        return False

@login_required
def delete_project(request, pk):
    Reporting.objects.filter(id=pk).update(active=0)
    return redirect('reportwriter:project_list')

@login_required
def activate_project(request, pk):
    Reporting.objects.filter(id=pk).update(active=1)
    return redirect('reportwriter:project_list')

@login_required
def run_quote(request, pk):
    Reporting.objects.filter(id=pk).update(quote_produced=1)
    project_specifics=Reporting.objects.get(id=pk)
    mailmergefunction_quotes(project_specifics, pk)
    return redirect('reportwriter:project_list')

@login_required
def download_quote(request, pk):
# def download_report(request, pk):
#     Reporting.objects.filter(id=pk)
    # Define Django project base directory
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Define text file name
    project_specifics=Reporting.objects.get(id=pk)
    filename = f"Q{pk}-{project_specifics.project_name}.pdf"
    # filename = 'template.docx'
    # Define the full file path
    filepath = BASE_DIR + '/templates/Application1/testfiles/' + filename
    # Open the file for reading content
    path = open(filepath, 'rb')
    # path = open(filepath, 'r', encoding="utf8")
    # Set the mime type
    # mime_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    # mime_type="application/pdf"
    mime_type, _ = mimetypes.guess_type(filepath)
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    # response['Content-Encoding'] = 'UTF-8'
    # response['Content-Length'] = len(path)
    # response['Errors']= 'ignore'
    # Return the response value
    Reporting.objects.filter(id=pk).update(quote_issued=1)
    # redirect('reportwriter:project_list')
    return response

@login_required
def dl_and_refresh(request, pk):
    download_quote(request, pk)
    return redirect('reportwriter:project_list')

@login_required
def quote_accepted(request, pk):
    Reporting.objects.filter(id=pk).update(quote_accepted=1)
    return redirect('reportwriter:project_list')

@login_required
def generate_report(request, pk):
    Reporting.objects.filter(id=pk).update(report_generated=1)
    project_specifics = Reporting.objects.get(id=pk)
    mailmergefunction_reports(project_specifics, pk)
    return redirect('reportwriter:project_list')

@login_required
def download_report(request, pk):
    #     Reporting.objects.filter(id=pk)
    # Define Django project base directory
    Reporting.objects.filter(id=pk).update(report_issued=1)
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Define text file name
    project_specifics=Reporting.objects.get(id=pk)
    filename = f"PRJ{pk}-{project_specifics.project_name}.pdf"
    # filename = 'template.docx'
    # Define the full file path
    filepath = BASE_DIR + '/templates/Application1/testfiles/' + filename
    # Open the file for reading content
    path = open(filepath, 'rb')
    # path = open(filepath, 'r', encoding="utf8")
    # Set the mime type
    # mime_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    # mime_type="application/pdf"
    mime_type, _ = mimetypes.guess_type(filepath)
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    # response['Content-Encoding'] = 'UTF-8'
    # response['Content-Length'] = len(path)
    # response['Errors']= 'ignore'
    # Return the response value
    return response

ProiectFinal/ProiectWebFinal/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, TemplateView

class CreateHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'home/home_page.html'

class CreateAboutView(TemplateView):
    template_name = 'home/about_page.html'

ProiectFinal/ProiectWebFinal/templates/Application1/assign_engineer.html
{% extends 'base2.html' %}
{% block content %}
    <div class="w3-center w3-hide-small">
    <form method="POST" class="w3-container w3-card-4 w3-light-grey">
        {% csrf_token %}
        {% for field in form %}
        <label class="w3-text-grey"><b>{{field.label}}</b></label>
            {{ field }} {{ field.errors }} <br>
            <br>
        {% endfor %}
        <button class="w3-btn w3-grey w3-hover-green w3-round-xlarge" type="submit">Update Project</button>
    </form>
    </div>
{% endblock %}

ProiectFinal/ProiectWebFinal/templates/Application1/home.html
{% extends 'base.html' %}
{% block content %}
    <nav>
    {% if request.user.is_authenticated %}
        <a class="btn" href="{% url 'reportwriter:project_list' %}">Live Projects</a>
        <a class="btn" href="{% url 'reportwriter:closed_projects' %}">Closed Projects</a>
    {% endif %}
    </nav>
{% endblock %}

ProiectFinal/ProiectWebFinal/templates/Application1/project_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br>
            <br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

ProiectFinal/ProiectWebFinal/templates/Application1/projects_index.html
{% extends 'base2.html' %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <nav>
    {% if request.user.is_authenticated %}
        <a class="w3-button w3-grey w3-hover-black" href="{% url 'reportwriter:project_list' %}">Live Projects</a>
        <a class="w3-button w3-grey w3-hover-black" href="{% url 'reportwriter:closed_projects' %}">Closed Projects</a>
    {% endif %}
    </nav>
    <br>
    <a class="w3-button w3-black w3-hover-grey" href="{% url 'reportwriter:add_project' %}">Add project</a>
    <table class="w3-table-all w3-hoverable w3-card-4 w3-centered w3-bordered">
        <thead>
            <tr class="w3-grey">
                <th>Index</th>
                <th>Project Name</th>
                <th>Project Value (£m)</th>
                <th>Project Type</th>
                <th>Client</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in projects %}      <!--Aici se foloseste numele modelului + _ + list-->
                    <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                    <td>{{ item.project_name }}</td>
                    <td>{{ item.project_value }}</td>
                    <td>{{ item.building_type }}</td>
                    <td>{{ item.client_company }}</td>
                    <td><a href="{% url 'reportwriter:modify_project' item.id %}" class="w3-button w3-khaki w3-hover-grey w3-round-xlarge">Modify Project</a>
                        {% if item.active == 1 %}
                            <a href="{% url 'reportwriter:delete_project' item.id %}" class="w3-button w3-khaki w3-hover-red w3-round-xlarge">Delete Project</a>
                        {% else %}
                            <a href="{% url 'reportwriter:activate_project' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Activate Project</a>
                        {% endif %}
                        {% if item.quote_produced == 0 %}
                            <a href="{% url 'reportwriter:generate_quote' item.id %}" class="w3-button w3-khaki w3-hover-blue w3-round-xlarge">Generate Quote</a>
                        {% else %}
                            {% if item.quote_issued == 0 %}
                                <a href="{% url 'reportwriter:download_quote' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Download Quote</a>
                            {% else %}
                                <a class="w3-button w3-disabled" disabled>Quote Issued</a>
                            {% endif %}
                        {% endif %}
                        {% if item.quote_issued == 0 %}
                            <a class="w3-button w3-disabled" disabled>Quote Accepted</a>
                        {% else %}
                            {% if item.quote_accepted == 0 %}
                                <a href="{% url 'reportwriter:quote_accepted' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Quote Accepted</a>
                            {% else %}
                                {% if item.assigned_engineer == 'NA' %}
                                    <a href="{% url 'reportwriter:assign_engineer' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Assign Engineer</a>
                                {% else %}
                                    {% if item.report_generated == 0 %}
                                        <a href="{% url 'reportwriter:generate_report' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Generate Report</a>
                                    {% else %}
                                        <a href="{% url 'reportwriter:download_report' item.id %}" class="w3-button w3-khaki w3-hover-green w3-round-xlarge">Download Report</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endif %}
                        </td>
                    <td></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
    <div class="w3-center w3-grey" >
        <div class="w3-bar">
            {% if page_obj.has_previous %}
                <a class='w3-button w3-circle w3-teal' href='?page={{ page_obj.previous_page_number}}'><<</a>
            {% else %}
                <a class='w3-button w3-circle w3-teal w3-disabled'><span><<</span></a>
            {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <a class="'w3-button w3-button w3-round-xxlarge w3-pale-green"><span>{{ i }}<span class='sr-only'>(curent)</span></span></a>
            {% else %}
                <a class="w3-button w3-circle w3-teal" href="?page={{ i }}">{{ i }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="w3-button w3-circle w3-teal" href="?page={{ page_obj.next_page_number }}">>></a>
        {% else %}
            <a class="w3-button w3-circle w3-teal w3-disabled"><span>>></span></a>
        {% endif %}
        <a class="align-right">Showing projects {{ page_obj.start_index }} - {{ page_obj.end_index}} of {{ page_obj.paginator.count }}</a>
        </div>
    </div>
    {% endif %}
{% endblock %}